# MT(MOD_LCTL | MOD_LSFT | MOD_LALT | MOD_LGUI,KC_ENT)
after-startup-command = ['exec-and-forget open -a Wezterm', 'workspace t']
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[mode.main.binding]
    cmd-alt-ctrl-shift-enter ='exec-and-forget aerospace reload-config'

    cmd-alt-ctrl-slash = 'layout tiles'
    cmd-alt-ctrl-comma = 'layout accordion'
    cmd-alt-ctrl-shift-v = 'split vertical'

    cmd-alt-ctrl-h = 'focus left'
    cmd-alt-ctrl-j = 'focus down'
    cmd-alt-ctrl-k = 'focus up'
    cmd-alt-ctrl-l = 'focus right'

    cmd-alt-ctrl-shift-h = 'move left'
    cmd-alt-ctrl-shift-j = 'move down'
    cmd-alt-ctrl-shift-k = 'move up'
    cmd-alt-ctrl-shift-l = 'move right'

    cmd-alt-ctrl--minus = 'resize smart -50'
    cmd-alt-ctrl--equal = 'resize smart +50'
    cmd-alt-ctrl-shift-g = ['exec-and-forget open -a Supacode', 'workspace t']
    alt-shift-b = ['exec-and-forget open -a Google\ Chrome', 'workspace b']

    cmd-alt-ctrl-b = 'workspace b'
    cmd-alt-ctrl-w = 'workspace w'
    cmd-alt-ctrl-e = 'workspace e'
    cmd-alt-ctrl-t = 'workspace t'
    cmd-alt-ctrl-i = 'workspace i'
    cmd-alt-ctrl-o = 'workspace o'

    cmd-alt-ctrl-shift-b = 'move-node-to-workspace b'
    cmd-alt-ctrl-shift-w = 'move-node-to-workspace w'
    cmd-alt-ctrl-shift-e = 'move-node-to-workspace e'
    cmd-alt-ctrl-shift-t = 'move-node-to-workspace t'
    cmd-alt-ctrl-shift-i = 'move-node-to-workspace i'
    cmd-alt-ctrl-shift-o = 'move-node-to-workspace o'

    [workspace-to-monitor-force-assignment]

    b = 'main'
    w = 'main'
    e = 'main'

    t = ['secondary', 'main']
    i = ['secondary', 'main']
    o = ['secondary', 'main']


    # alt-tab = 'workspace-back-and-forth'
    cmd-alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # alt-shift-semicolon = 'mode service'
    cmd-alt-ctrl-shift-s = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']


    cmd-alt-ctrl-shift-h = ['join-with left', 'mode main']
    cmd-alt-ctrl-shift-j = ['join-with down', 'mode main']
    cmd-alt-ctrl-shift-k = ['join-with up', 'mode main']
    cmd-alt-ctrl-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
if.app-id = 'app.supabit.supacode'
run = 'move-node-to-workspace t'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace t'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace t'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
if.window-title-regex-substring = '^Quick Terminal$'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = 'move-node-to-workspace o'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace b'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace b'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace w'
