"$schema" = "https://starship.rs/config-schema.json"

palette = "mellow"

add_newline = false

[os]
disabled = false

[os.symbols]
Macos = "[󰒃 ](fg:spark)"

[directory]
truncation_symbol = "󰝰 "
truncation_length = 2
truncate_to_repo = true
style = "fg:frost"
format = "[$path]($style) "

[git_branch]
symbol = ""
style = "fg:spark"
format = "[[$symbol $branch ](fg:spark)]($style)"

[git_status]
format = "$all_status$ahead_behind"
conflicted = "| [ $count ](fg:nova)"
ahead = "| [ $count ](fg:nova)"
behind = "| [ $count ](fg:nova)"
diverged = "| [ $ahead_count  $behind_count ](fg:nova)"
untracked = "| [󱡬 $count ](fg:nova)"
stashed = "| [󰒲 $count ](fg:nova)"
modified = "| [󰏫 $count ](fg:nova)"
staged = "| [󰱒 $count ](fg:nova)"
renamed = "| [󰁕 $count ](fg:nova)"
deleted = "| [󰍵 $count ](fg:nova)"

[character]
disabled = false
success_symbol = "[󱕴](fg:spark)"
error_symbol = "[󱦃](fg:ember)"
vimcmd_symbol = "[󰌇](fg:lime)"
vimcmd_replace_one_symbol = "[󱆞](fg:iris)"
vimcmd_replace_symbol = "[󰌈](fg:iris)"
vimcmd_visual_symbol = "[󱆟](fg:spark)"

[palettes.mellow]
# Accent Colors
lychee  = "#ffccdd"
guava   = "#ffaa99"
fizz    = "#ff99ee"
nebula  = "#dd88ff"
ember   = "#ff6666"
cinder  = "#ee7777"
torch   = "#ffaa77"
spark   = "#ffdd88"
lime    = "#88ff99"
surge   = "#77ffcc"
pulse   = "#99eeff"
frost   = "#77ccff"
nova    = "#8899ff"
iris    = "#aa88ff"
# Base Colors
text    = "#ffffff"
sub1    = "#eeeeee"
sub0    = "#dddddd"
ov2     = "#cccccc"
ov1     = "#bbbbbb"
ov0     = "#aaaaaa"
surf2   = "#999999"
surf1   = "#888888"
surf0   = "#777777"
base    = "#222222"
mantle  = "#111111"
crust   = "#000000"
